// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nails.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nails.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", "platform");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", "identity");
                });

            modelBuilder.Entity("Nails.Infrastructure.Modules.Catalog.Entities.BeautyService", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_services_category_id");

                    b.ToTable("services", "catalog");

                    b.HasData(
                        new
                        {
                            Id = "manicure-classic",
                            CategoryId = "nails",
                            Name = "Маникюр классический",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "manicure-gel",
                            CategoryId = "nails",
                            Name = "Маникюр с покрытием гель-лак",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "nail-extension",
                            CategoryId = "nails",
                            Name = "Наращивание ногтей",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "pedicure-classic",
                            CategoryId = "nails",
                            Name = "Педикюр классический",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = "pedicure-gel",
                            CategoryId = "nails",
                            Name = "Педикюр с покрытием гель-лак",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = "nail-design",
                            CategoryId = "nails",
                            Name = "Дизайн ногтей",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = "brow-correction",
                            CategoryId = "brows",
                            Name = "Коррекция бровей",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "brow-tint",
                            CategoryId = "brows",
                            Name = "Окрашивание бровей",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "brow-lamination",
                            CategoryId = "brows",
                            Name = "Ламинирование бровей",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "brow-permanent",
                            CategoryId = "brows",
                            Name = "Перманентный макияж бровей",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = "lash-extension-classic",
                            CategoryId = "lashes",
                            Name = "Наращивание ресниц, классика",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "lash-extension-volume",
                            CategoryId = "lashes",
                            Name = "Наращивание ресниц, объём",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "lash-lamination",
                            CategoryId = "lashes",
                            Name = "Ламинирование ресниц",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "lash-tint",
                            CategoryId = "lashes",
                            Name = "Окрашивание ресниц",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = "face-cleansing",
                            CategoryId = "cosmetology",
                            Name = "Чистка лица",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "face-peeling",
                            CategoryId = "cosmetology",
                            Name = "Пилинг лица",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "face-massage",
                            CategoryId = "cosmetology",
                            Name = "Массаж лица",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "face-care",
                            CategoryId = "cosmetology",
                            Name = "Уходовая процедура для лица",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = "makeup-day",
                            CategoryId = "makeup",
                            Name = "Дневной макияж",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "makeup-evening",
                            CategoryId = "makeup",
                            Name = "Вечерний макияж",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "makeup-wedding",
                            CategoryId = "makeup",
                            Name = "Свадебный макияж",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "sugaring",
                            CategoryId = "depilation",
                            Name = "Шугаринг",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "wax-depilation",
                            CategoryId = "depilation",
                            Name = "Восковая депиляция",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "laser-hair-removal",
                            CategoryId = "depilation",
                            Name = "Лазерная эпиляция",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("Nails.Infrastructure.Modules.Catalog.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", "catalog");

                    b.HasData(
                        new
                        {
                            Id = "nails",
                            Name = "Ногти",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "brows",
                            Name = "Брови",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "lashes",
                            Name = "Ресницы",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "cosmetology",
                            Name = "Косметология",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = "makeup",
                            Name = "Макияж",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = "depilation",
                            Name = "Депиляция",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("Nails.Infrastructure.Modules.Catalog.Entities.City", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.ToTable("cities", "catalog");

                    b.HasData(
                        new
                        {
                            Id = "minsk",
                            Name = "Минск",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "brest",
                            Name = "Брест",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "vitebsk",
                            Name = "Витебск",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "gomel",
                            Name = "Гомель",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = "grodno",
                            Name = "Гродно",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = "mogilev",
                            Name = "Могилёв",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = "baranovichi",
                            Name = "Барановичи",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = "bobruisk",
                            Name = "Бобруйск",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = "borisov",
                            Name = "Борисов",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = "pinsk",
                            Name = "Пинск",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = "orsha",
                            Name = "Орша",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = "mozyr",
                            Name = "Мозырь",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = "soligorsk",
                            Name = "Солигорск",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = "novopolotsk",
                            Name = "Новополоцк",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = "lida",
                            Name = "Лида",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = "molodechno",
                            Name = "Молодечно",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = "polotsk",
                            Name = "Полоцк",
                            SortOrder = 17
                        },
                        new
                        {
                            Id = "zhlobin",
                            Name = "Жлобин",
                            SortOrder = 18
                        },
                        new
                        {
                            Id = "svetlogorsk",
                            Name = "Светлогорск",
                            SortOrder = 19
                        },
                        new
                        {
                            Id = "rechitsa",
                            Name = "Речица",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = "slutsk",
                            Name = "Слуцк",
                            SortOrder = 21
                        },
                        new
                        {
                            Id = "zhodino",
                            Name = "Жодино",
                            SortOrder = 22
                        });
                });

            modelBuilder.Entity("Nails.Infrastructure.Modules.Identity.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("Nails.Infrastructure.Modules.Identity.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", "identity");
                });

            modelBuilder.Entity("Nails.Infrastructure.Modules.Masters.Entities.MasterProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("about");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("CityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_profiles_city_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_profiles_created_at");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_user_id");

                    b.ToTable("profiles", "masters");
                });

            modelBuilder.Entity("Nails.Infrastructure.Modules.Masters.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("PriceKind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("price_kind");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("service_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_offers");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_offers_category_id");

                    b.HasIndex("MasterId", "ServiceId")
                        .IsUnique()
                        .HasDatabaseName("ix_offers_master_id_service_id");

                    b.HasIndex("ServiceId", "Price")
                        .HasDatabaseName("ix_offers_service_id_price");

                    b.ToTable("offers", "masters");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Nails.Infrastructure.Modules.Identity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Nails.Infrastructure.Modules.Identity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Nails.Infrastructure.Modules.Identity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("Nails.Infrastructure.Modules.Catalog.Entities.BeautyService", b =>
                {
                    b.HasOne("Nails.Infrastructure.Modules.Catalog.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_services_category_category_id");
                });

            modelBuilder.Entity("Nails.Infrastructure.Modules.Identity.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Nails.Infrastructure.Modules.Identity.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenant_tenant_id");
                });

            modelBuilder.Entity("Nails.Infrastructure.Modules.Masters.Entities.Offer", b =>
                {
                    b.HasOne("Nails.Infrastructure.Modules.Masters.Entities.MasterProfile", null)
                        .WithMany()
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_offers_profiles_master_id");
                });
#pragma warning restore 612, 618
        }
    }
}
